### ISSUE TITLE
TypeError: pc.parseFromUrl is not a function

### ISSUE THREAD

**Issue by akaleeroy** [ArcaneDigital/Page-Content#1]
Just installed and tried the usage example and got

```
pc.parseFromUrl('http://example.com').then(res => {
   ^

TypeError: pc.parseFromUrl is not a function
    at Object.<anonymous> (D:\Config\Desktop\page-content-test\index.js:3:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```
Windows x64, NodeJS v10.5.0

**Comment by jaygoodfellow** [comment]
The documentation was wrong, function should be **parseFromURL**. I've updated the docs, thanks for the feedback.
